export const data = [
  {
    id: 1,
    name: 'Pickled Tuna Feast',
    description: 'ทูน่าดองสูตรพิเศษสำหรับแมว อุดมด้วยโอเมก้า 3 และโปรตีนสูง',
    price: 250,
    discount: 0,
    stock: 13,
    category: 'อาหารแมวพรีเมียม',
    option: ['สูตรดั้งเดิม', 'สูตรโอเมก้า+', 'สูตรลดกลิ่น'],
    sizes: ['150g', '300g', '500g'],
    images: [
      'https://img2.pic.in.th/pic/Tuna.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/Chicken2.jpeg',
      'https://img2.pic.in.th/pic/Chicken3.jpeg',
    ],
  },
  {
    id: 2,
    name: 'Pickled Chicken Bites',
    description: 'ขนมขบเคี้ยวเนื้อไก่หมักสูตรพิเศษ อ่อนโยนต่อระบบย่อยของแมว',
    price: 180,
    discount: 10,
    stock: 13,
    category: 'อาหารแมวพรีเมียม',
    option: ['สูตรดั้งเดิม', 'สูตรบำรุงลำไส้', 'สูตรไร้เกลือ'],
    sizes: ['100g', '200g', '400g'],
    images: [
      'https://img2.pic.in.th/pic/Chicken.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/Tuna2.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/Tuna4.jpeg',
    ],
  },
  {
    id: 3,
    name: 'Freeze-Dried Salmon Cube',
    description: 'แซลมอนฟรีซดราย 100% กรอบนอกนุ่มใน อุดมด้วยโอเมก้า 3',
    price: 320,
    discount: 5,
    stock: 13,
    category: 'อาหารแมวพรีเมียม',
    option: ['สูตรดั้งเดิม', 'สูตรบำรุงขน', 'สูตรควบคุมน้ำหนัก'],
    sizes: ['120g', '240g', '360g'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Salmon.jpeg',
      'https://img2.pic.in.th/pic/Salmon2.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/Salmon3.jpeg',
    ],
  },
  {
    id: 4,
    name: 'Sweet Potato Cat Treat',
    description: 'ขนมมันหวานอบกรอบ เสริมไฟเบอร์ ช่วยย่อยอาหาร',
    price: 150,
    discount: 0,
    stock: 13,
    category: 'อาหารแมวพรีเมียม',
    option: ['สูตรดั้งเดิม', 'สูตรกลิ่นวานิลลา', 'สูตรเสริมวิตามิน'],
    sizes: ['80g', '160g', '240g'],
    images: [
      'https://img2.pic.in.th/pic/Sweet-Potato.png',
      'https://example.com/images/2.jpg',
      'https://example.com/images/3.jpg',
    ],
  },
  {
    id: 5,
    name: 'Lobster Cat Jelly',
    description: 'เยลลี่รสล็อบสเตอร์สุดหรู เพิ่มความชุ่มชื้นให้ร่างกายแมว',
    price: 220,
    discount: 10,
    stock: 13,
    category: 'อาหารแมวพรีเมียม',
    option: ['สูตรล็อบสเตอร์', 'สูตรล็อบสเตอร์+วิตามิน', 'สูตรลดกลิ่นฉี่'],
    sizes: ['4 ซอง', '8 ซอง', '12 ซอง'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/lobster-jelly.png',
      'https://img2.pic.in.th/pic/lobster-jelly2.jpg',
      'https://example.com/images/3.jpg',
    ],
  },
  {
    id: 6,
    name: 'Interactive Fishing Rod',
    description: 'คันเบ็ดตกปลาแมว มีขนนกและกระดิ่งดึงดูดความสนใจ',
    price: 199,
    discount: 0,
    stock: 13,
    category: 'ของเล่นแมว',
    option: ['แบบขนนก', 'แบบกระดิ่ง', 'แบบเลเซอร์'],
    sizes: ['สั้น', 'กลาง', 'ยาว'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Cat-Bait.jpeg',
      'https://img2.pic.in.th/pic/Cat-Bait2.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/Cat-Bait3.jpeg',
    ],
  },
  {
    id: 7,
    name: 'Pickled Yarn Ball',
    description: 'ลูกบอลไหมพรมกลิ่นปลาหมัก ดึงดูดให้แมวเล่นได้นานขึ้น',
    price: 150,
    discount: 5,
    stock: 13,
    category: 'ของเล่นแมว',
    option: ['กลิ่นปลาหมึก', 'กลิ่นปลาทู', 'กลิ่นแมวขี้เกลือ'],
    sizes: ['เล็ก', 'กลาง', 'ใหญ่'],
    images: [
      'https://img2.pic.in.th/pic/Yarn-Ball3.jpeg',
      'https://img2.pic.in.th/pic/Yarn-Ball.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/Yarn-Ball2.jpeg',
    ],
  },
  {
    id: 8,
    name: 'Wate Fountain',
    description: 'น้ำพุสำหรับแมว สวยงาม ทำให้การดื่มน้ำไม่มีเบื่อ',
    price: 890,
    discount: 10,
    stock: 13,
    category: 'ของเล่นแมว',
    option: ['สีขาว', 'สีดำ'],
    sizes: ['ขนาดเล็ก', 'ขนาดกลาง', 'ขนาดใหญ่'],
    images: [
      'https://img2.pic.in.th/pic/water1d623dd73124150b.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/water-2.jpeg',
      'https://img2.pic.in.th/pic/Cat-Maze2.jpg',
    ],
  },
  {
    id: 9,
    name: 'Pickled Mouse Chase',
    description: 'หนูปลอมกลิ่นหมัก ขยับได้เมื่อแมวตบ',
    price: 350,
    discount: 0,
    stock: 13,
    category: 'ของเล่นแมว',
    option: ['กลิ่นปลา', 'กลิ่นไก่', 'กลิ่นชีส'],
    sizes: ['เล็ก', 'กลาง', 'ใหญ่'],
    images: [
      'https://img2.pic.in.th/pic/Cat-Mouse.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/Cat-Mouse2.jpeg',
      'https://img2.pic.in.th/pic/Cat-Mouse3.jpeg',
    ],
  },
  {
    id: 10,
    name: 'Hide & Seek Tunnel',
    description: 'อุโมงค์ผ้าลายดองเกลือสำหรับเล่นซ่อนแอบ',
    price: 790,
    discount: 15,
    stock: 13,
    category: 'ของเล่นแมว',
    option: ['ลายปลาหมัก', 'ลายโหลดอง', 'ลายขี้เกลือ'],
    sizes: ['90cm', '120cm', '150cm'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Cat-Tunnel.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Cat-Tunnel3.jpg',
      'https://img2.pic.in.th/pic/Cat-Tunnel2.jpg',
    ],
  },
  {
    id: 11,
    name: 'Vintage Cat Cave',
    description: 'เต็นท์แมวผ้าลายวินเทจ พร้อมเบาะนุ่ม',
    price: 1290,
    discount: 0,
    stock: 13,
    category: 'Cat Beds & Condos',
    option: ['Vintage', 'classic Tent', 'Boho Style'],
    sizes: ['S', 'M', 'L'],
    images: [
      'https://img2.pic.in.th/pic/Cat-Tent.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Cat-Tent2.jpg',
      'https://img2.pic.in.th/pic/Cat-Tent3.jpg',
    ],
  },
  {
    id: 12,
    name: 'Pickled Cat Hammock',
    description: 'เปลญวนสำหรับแมว นอนเล่นได้ทุกมุม',
    price: 890,
    discount: 0,
    stock: 13,
    category: 'Cat Beds & Condos',
    option: ['Hammock', 'Hanging Cradle', 'Foldable Net'],
    sizes: ['S', 'M', 'L'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Cat-Hammock.jpg',
      'https://img2.pic.in.th/pic/Cat-Hammock2.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Cat-Hammock3.jpg',
    ],
  },
  {
    id: 13,
    name: 'Pickled Barrel Bed',
    description: 'ที่นอนทรงถังไม้ดองเกลือ ด้านในมีเบาะนุ่มให้แมวซุกตัว',
    price: 1490,
    discount: 10,
    stock: 13,
    category: 'Cat Beds & Condos',
    option: ['Barrel', 'Rustic Drum', 'Vintage Canister'],
    sizes: ['S', 'M', 'L'],
    images: [
      'https://img2.pic.in.th/pic/barrel2.jpeg',
      'https://img2.pic.in.th/pic/barrel.jpeg',
      'https://img5.pic.in.th/file/secure-sv1/barrel3.jpeg',
    ],
  },
  {
    id: 14,
    name: 'Ancient Fortress Condo',
    description: 'คอนโดแมวลายปราสาทโบราณ มีเสาหลักและพื้นที่ซ่อนตัว',
    price: 2290,
    discount: 15,
    stock: 13,
    category: 'Cat Beds & Condos',
    option: ['Fortress', 'Castle Style', 'Royal Den'],
    sizes: ['M', 'L', 'XL'],
    images: [
      'https://img2.pic.in.th/pic/Castle-Condo3.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Castle-Condo2.jpg',
      'https://img2.pic.in.th/pic/Castle-Condo.jpg',
    ],
  },
  {
    id: 15,
    name: 'Pickled Bread Bed',
    description: 'ที่นอนทรงขนมปังดองเกลือ นุ่มฟู ให้แมวหนุนสบาย',
    price: 990,
    discount: 0,
    stock: 13,
    category: 'Cat Beds & Condos',
    option: ['Bread Shape', 'Toasted Style', 'Jam Swirl'],
    sizes: ['S', 'M', 'L'],
    images: [
      'https://img2.pic.in.th/pic/Cat-Bed3.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Cat-Bed4.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Cat-Bed2.jpgg',
    ],
  },
  {
    id: '16',
    name: 'Pickled Cat T-shirt',
    description: 'เสื้อยืดลายแมวดองเกลือ พิมพ์ลายสีติดทนนาน',
    price: 450,
    discount: 0,
    stock: 13,
    category: 'Apparel & Accessories',
    option: ['Pickled Tuna', 'Pickled Salmon', 'Pickled Shrimp'],
    sizes: ['S', 'M', 'L'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Cat-Shirt4.jpg',
      'https://img2.pic.in.th/pic/Cat-Shirt3.jpg',
      'https://img2.pic.in.th/pic/Cat-Shirt.jpg',
    ],
  },
  {
    id: '17',
    name: 'Pickled Cat Mask',
    description: 'หน้ากากแมวดองเกลือสไตล์วินเทจ ใส่คู่กับเสื้อธีมเดียวกัน',
    price: 290,
    discount: 0,
    stock: 13,
    category: 'Apparel & Accessories',
    option: ['Vintage Sepia', 'Classic Black', 'Pickled Pink'],
    sizes: ['S', 'M', 'Free Size'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Cat-Mask.jpg',
      'https://img2.pic.in.th/pic/Cat-Mask2.png',
      'https://example.com/images/3.jpg',
    ],
  },
  {
    id: '18',
    name: 'Vintage Cloak for Cats',
    description: 'เสื้อคลุมแมวสไตล์โบราณ ใส่แล้วเหมือนแมวพ่อค้าเร่',
    price: 690,
    discount: 0,
    stock: 13,
    category: 'Apparel & Accessories',
    option: ['Golden Brown', 'Classic Navy', 'Pickled Plum'],
    sizes: ['S', 'M', 'L'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/vintage-cloak2.jpg',
      'https://img2.pic.in.th/pic/vintage-cloak3.jpg',
      'https://img2.pic.in.th/pic/vintage-cloak5.jpg',
    ],
  },
  {
    id: '19',
    name: 'Pickled Cat Bowtie',
    description: 'โบว์หูกระต่ายลายปลาหมัก คลาสสิกสุดๆ',
    price: 250,
    discount: 0,
    stock: 13,
    category: 'Apparel & Accessories',
    option: ['Pickled Fish', 'Tuna Pattern', 'Shrimp Classic'],
    sizes: ['S', 'M', 'Free Size'],
    images: [
      'https://img2.pic.in.th/pic/Bow-Ribbon3.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Bow-Ribbon2.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Bow-Ribbon4.jpg',
    ],
  },
  {
    id: '20',
    name: 'Old-School Fisherman Hat',
    description:
      'หมวกสานแมวธีมชาวประมงโบราณ ใส่แล้วเข้ากับบรรยากาศร้านดองเกลือ',
    price: 390,
    discount: 0,
    stock: 13,
    category: 'Apparel & Accessories',
    option: ['Woven Natural', 'Pickled Blue', 'Sea Brown'],
    sizes: ['S', 'M', 'Free Size'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/old-school-hat.jpg',
      'https://img2.pic.in.th/pic/old-school-hat-2.jpgg',
      'https://example.com/images/3.jpg',
    ],
  },
  {
    id: '21',
    name: 'Pickled Cat Clay Figurine',
    description: 'ตุ๊กตาดินเผาแมวดองเกลือ งานทำมือสุดคลาสสิก',
    price: 890,
    discount: 10,
    stock: 13,
    category: 'Collectibles & Home Decor',
    option: ['Handmade', 'Limited Edition', 'Natural Finish'],
    sizes: ['S', 'M', 'L'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Cat-Jar-3.jpg',
      'https://img2.pic.in.th/pic/Cat-Jar.jpg',
      'https://img2.pic.in.th/pic/Cat-Jar-2.jpg',
    ],
  },
  {
    id: '22',
    name: 'Hand-Painted Pickled Cat Plate',
    description: 'จานเซรามิกลายแมวดองเกลือ งานเพ้นท์มือสุดประณีต',
    price: 650,
    discount: 15,
    stock: 13,
    category: 'Collectibles & Home Decor',
    option: ['Standard', 'Special Edition', 'Gold Rim'],
    sizes: ['S (dessert)', 'M (lunch)', 'L (dinner)'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/cat-plate.jpg',
      'https://img5.pic.in.th/file/secure-sv1/cat-plate-2.jpg',
      'https://img2.pic.in.th/pic/cat-plate-3.jpg',
    ],
  },
  {
    id: '23',
    name: 'Vintage Pickled Cat Clock',
    description: 'นาฬิกาแขวนลายแมวดองเกลือ งานวินเทจเหมือนยุค 80s',
    price: 1190,
    discount: 15,
    stock: 13,
    category: 'Collectibles & Home Decor',
    option: ['Standard', 'Roman Dial', 'Antique Finish'],
    sizes: ['S (mini)', 'M (wall)', 'L (mantel)'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Vintage-Clock.jpg',
      'https://img2.pic.in.th/pic/cat-clock-3.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Cat-Clock-2.png',
    ],
  },
  {
    id: '24',
    name: 'Pickled Cat Wooden Frame',
    description: 'กรอบรูปไม้สลักลายแมวดองเกลือ สวยงามสำหรับตกแต่งบ้าน',
    price: 990,
    discount: 0,
    stock: 13,
    category: 'Collectibles & Home Decor',
    option: ['Standard', 'Carved Style', 'Vintage Paint'],
    sizes: ['S (4x6)', 'M (5x7)', 'L (8x10)'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Cat-Wooden-Frame.jpg',
      'https://img2.pic.in.th/pic/Cat-Wooden-Frame-2.jpg',
      'https://example.com/images/3.jpg',
    ],
  },
  {
    id: '25',
    name: 'Pickled Cat Ceramic Jar',
    description: 'โหลเซรามิกใส่อาหารหรือน้ำชา ลายแมวดองเกลือ',
    price: 790,
    discount: 5,
    stock: 13,
    category: 'Collectibles & Home Decor',
    option: ['Standard', 'Bamboo Lid', 'Floral Print'],
    sizes: ['S (tea)', 'M (cookies)', 'L (storage)'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/Cat-Jar-3.jpg',
      'https://img2.pic.in.th/pic/Cat-Jar.jpg',
      'https://img2.pic.in.th/pic/Cat-Jar-2.jpg',
    ],
  },
  {
    id: '26',
    name: 'Pickled Cat Aroma Candle',
    description: 'เทียนหอมกลิ่นสมุนไพรดอง ช่วยผ่อนคลาย',
    price: 490,
    discount: 10,
    stock: 13,
    category: 'Pickled Cat Gift & Special Items',
    option: ['Standard', 'Herbal Infusion', 'Vintage Glass'],
    sizes: ['S (travel)', 'M (home)', 'L (gift set)'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/aroma-candle-2.jpeg',
      'https://img2.pic.in.th/pic/aroma-candle.jpeg',
      'https://example.com/images/3.jpg',
    ],
  },
  {
    id: '27',
    name: 'Pickled Cat Mug',
    description:
      'แก้วมักลายแมวดองเกลือพร้อมฝาปิดเซรามิก สวยน่ารักเหมาะกับทุกวัน',
    price: 450,
    discount: 10,
    stock: 13,
    category: 'Pickled Cat Gift & Special Items',
    option: ['Standard', 'Matte Finish', 'Wooden Lid'],
    sizes: ['S (espresso)', 'M (regular)', 'L (tall)'],
    images: [
      'https://img2.pic.in.th/pic/Cat_Mug.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Cat_Mug4.jpg',
      'https://img5.pic.in.th/file/secure-sv1/Cat_Mug2.jpg',
    ],
  },
  {
    id: '28',
    name: 'Pickled Cat Notebook',
    description: 'สมุดโน้ตปกผ้าลินินลายแมวดองเกลือ พร้อมหน้ากระดาษแบบวินเทจ',
    price: 390,
    discount: 10,
    stock: 13,
    category: 'Pickled Cat Gift & Special Items',
    option: ['Standard', 'Hardcover', 'Linen Bound'],
    sizes: ['S (A6)', 'M (A5)', 'L (B5)'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/notebook.jpg',
      'https://example.com/images/2.jpg',
      'https://example.com/images/3.jpg',
    ],
  },
  {
    id: '29',
    name: 'Pickled Cat Tote Bag',
    description:
      'กระเป๋าผ้าลินินลายปลาหมักและแมวดองเกลือ แข็งแรง ทนทาน ใส่ของได้เยอะ',
    price: 590,
    discount: 5,
    stock: 13,
    category: 'Pickled Cat Gift & Special Items',
    option: ['Standard', 'Foldable', 'Inner Pocket'],
    sizes: ['S (small carry)', 'M (daily)', 'L (shopping)'],
    images: [
      'https://img5.pic.in.th/file/secure-sv1/tote-bag.jpg',
      'https://img5.pic.in.th/file/secure-sv1/tote-bag-2.png',
      'https://img2.pic.in.th/pic/tote-bag-3.png',
    ],
  },
  {
    id: '30',
    name: 'Pickled Cat Soap Bar',
    description: 'สบู่ทำมือสูตรธรรมชาติ กลิ่นอ่อนโยน มีส่วนผสมจากสมุนไพรแท้ๆ',
    price: 250,
    discount: 10,
    stock: 13,
    category: 'Pickled Cat Gift & Special Items',
    option: ['Handmade', 'Limited Edition', 'Herbal Formula'],
    sizes: ['S (guest)', 'M (daily)', 'L (spa)'],
    images: [
      'https://img2.pic.in.th/pic/pc_soap1.jpg',
      'https://img5.pic.in.th/file/secure-sv1/pc_soap2.png',
      'https://img2.pic.in.th/pic/pc_soap3.png',
    ],
  },
];
